### ISSUE TITLE
[Login] User can sign up, sign in, and sign out with email

### ISSUE THREAD

**Issue by doliinyk** [doliinyk/cash-manager-backend#8]
# User story: Registration/Login

## Summary

As a User, I want to be able to sign up, sign in by email/login and password, sign out, so that will bring personal account features.

## Description

Backend:
- must provide API endpoints that will handle registration, login, logout, account activation, password reset;
- encrypt user password after registration;
- handle further authorization by credentials given after login;
- use email to communicate with user about activation/reset cases;
- email and login both have to be used as credentials to login;
- implement JWT authorization by access/refresh tokens model & different sign certs for them;
- implement token refreshing.

Frontend:
- must implement all pages/component of cases described above;
- consider intercepting HTTP request with auth tokens;
- validate request data (email, password) and be able to display validation errors that are coming from backend (e.g. duplicate email);
- support scheduled token refreshing.

## Tasks

- [x] Discuss security model
- [x] Implement registration on backend
- [x] Implement basic auth on backend
- [x] Implement JWT auth on backend
- [x] Implement activate/reset on backend
- [x] Implement registration/login page on frontend
- [x] Implement activate/reset on frontend
- [x] Implement intercepting/refreshing on frontend
